### PR TITLE
support mtl-2.3

### PR DESCRIPTION
**Pull request by locallycompact**

### CODE REVIEW

**Comment by Bodigrim** [comment]
@simonmar just a gentle reminder, `mtl-2.3` has been released quite a while ago.

**Comment by ocharles** [comment]
@simonmar ping. If you need help with this type of maintenance, I'm happy to help out.

**Comment by simonmar** [comment]
> @simonmar ping. If you need help with this type of maintenance, I'm happy to help out.

@ocharles thanks for the offer, added you as a collaborator

**Comment by ocharles** [comment]
@simonmar Thank you! Could you also add me as a maintainer on Hackage? I'm `OliverCharles` there.

**Comment by simonmar** [comment]
@ocharles Done

**Comment by TeofilC** [comment]
@ocharles just a friendly bump on this

**Comment by ocharles** [comment]
@TeofilC I'll get this out today

**Comment by TeofilC** [comment]
Many thanks everyone! Really appreciate it!

**Pull request merged**
